### ISSUE TITLE
Great styling !

### ISSUE THREAD

**Issue by MoradAbed** [WebAhead5/TODO-List-MMF#9]
Great job guys!
The styling is great but it's a bit confusing, 
the sorting button is a little far from the list, 
and when the user wants to enlist multiple tasks, the input field will go down so he needs to scroll in order to continue.

**Comment by Marwanrizik91** [comment]
i agree, the sorting button is off place, but its was just temporary, added it at the last moment. will fix that for sure,
and the second issue is happening because the UI is only mobile for now, will have add desktop support.
